const scenario = (feature, name, expected, matcher, source = 'vitest') => ({
  feature,
  scenario: name,
  expected,
  matcher,
  source,
});

const blocked = (feature, name, expected) =>
  scenario(feature, name, expected, null, 'blocked-qa-environment');

const manual = (feature, name, expected) => scenario(feature, name, expected, null, 'manual');

export const scenarios = [
  scenario(
    'Authentication',
    'Sign in form',
    'User can enter credentials and submit sign in',
    'offers password login',
    'playwright',
  ),
  scenario(
    'Authentication',
    'Sign up flow entry',
    'User can reach account creation and see required fields',
    'signup and login navigation',
    'playwright',
  ),
  scenario(
    'Authentication',
    'Email verification state',
    'Missing verification token shows a recovery action',
    'verification route exposes',
    'playwright',
  ),
  scenario(
    'Authentication',
    'Invalid request validation',
    'Malformed login input receives a structured validation error',
    'rejects malformed public payloads',
  ),
  blocked(
    'Authentication',
    'Sign up with email delivery',
    'Account is created and a verification email is sent',
  ),
  blocked(
    'Authentication',
    'Email verification',
    'Valid token activates the account and consumes the token',
  ),
  blocked(
    'Authentication',
    'Authenticated sign in',
    'Verified user enters the protected application',
  ),
  blocked('Authentication', 'Logout', 'Session is revoked and the user returns to authentication'),
  blocked(
    'Authentication',
    'Session persistence',
    'Refresh restores a valid session without exposing tokens',
  ),

  scenario(
    'Home / Feed',
    'Anonymous feed boundary',
    'Unauthenticated users cannot read the feed',
    'rejects anonymous access to /api/feed',
  ),
  blocked('Home / Feed', 'Feed loading', 'Authenticated user sees a feed response'),
  blocked('Home / Feed', 'Feed ordering', 'Feed items follow the approved cursor/ranking order'),
  blocked('Home / Feed', 'Empty feed', 'Empty feed renders a deliberate empty state'),
  blocked('Home / Feed', 'Refresh/reload', 'Feed remains consistent after reload'),

  blocked('Posts', 'Create post', 'Post is created and appears in the feed'),
  blocked('Posts', 'View post', 'Post details are displayed'),
  blocked('Posts', 'Edit post', 'Owner changes persist'),
  blocked('Posts', 'Delete post', 'Owner can delete the post and it disappears'),
  blocked('Posts', 'Like post', 'Like count increases and state changes'),
  blocked('Posts', 'Unlike post', 'Like count decreases and state changes'),
  blocked('Posts', 'Comment on post', 'Comment is persisted and displayed'),
  blocked('Posts', 'Delete comment', 'Comment owner can delete the comment'),
  blocked('Posts', 'Post ownership', 'A different user cannot edit or delete the post'),

  scenario(
    'Profile',
    'Protected profile boundary',
    'Unauthenticated users cannot read profile data',
    '/api/users/507f1f77bcf86cd799439011/profile',
    'vitest',
  ),
  blocked('Profile', 'Edit profile', 'Updated profile data persists'),
  blocked('Profile', 'Profile picture', 'Profile picture update persists'),
  blocked('Profile', 'Bio and details persistence', 'Bio and profile details remain after reload'),
  blocked('Profile', 'Posts tab', 'User posts are displayed'),
  blocked('Profile', 'Events tab', 'User events are displayed'),
  blocked('Profile', 'Projects tab', 'User projects are displayed'),

  scenario(
    'Search',
    'Search authorization boundary',
    'Unauthenticated users cannot search private campus data',
    'rejects anonymous access to /api/search',
    'vitest',
  ),
  blocked('Search', 'User search', 'Matching users are returned'),
  blocked('Search', 'Post search', 'Matching posts are returned'),
  blocked('Search', 'Team search', 'Matching teams are returned'),
  blocked('Search', 'Event search', 'Matching events are returned'),
  blocked('Search', 'No-result search', 'No-result state is rendered'),
  blocked('Search', 'Search validation', 'Invalid search input receives a validation error'),

  scenario(
    'Events',
    'Event authorization boundary',
    'Unauthenticated users cannot list events',
    'rejects anonymous access to /api/events',
    'vitest',
  ),
  blocked('Events', 'View events', 'Events list loads'),
  blocked('Events', 'Create event', 'Authorized user can create an event'),
  blocked('Events', 'Edit event', 'Event changes persist'),
  blocked('Events', 'Delete event', 'Owner can archive an event'),
  blocked('Events', 'Join event', 'User registration is persisted'),
  blocked('Events', 'Leave event', 'User registration is cancelled'),
  blocked('Events', 'Event details', 'Event details load correctly'),

  scenario(
    'Teams',
    'Team authorization boundary',
    'Unauthenticated users cannot list teams',
    'rejects anonymous access to /api/teams',
    'vitest',
  ),
  blocked('Teams', 'View teams', 'Teams list loads'),
  blocked('Teams', 'Create team', 'Authorized user can create a team'),
  blocked('Teams', 'Team details', 'Team details load'),
  blocked('Teams', 'Join team', 'Membership request is persisted'),
  blocked('Teams', 'Leave team', 'Membership is removed'),
  blocked('Teams', 'Membership authorization', 'Unauthorized membership changes are rejected'),

  scenario(
    'Projects',
    'Project authorization boundary',
    'Unauthenticated users cannot list projects',
    'rejects anonymous access to /api/projects',
    'vitest',
  ),
  blocked('Projects', 'Create project', 'Authorized user can create a project'),
  blocked('Projects', 'View project', 'Project details load'),
  blocked('Projects', 'Edit project', 'Project changes persist'),
  blocked('Projects', 'Delete project', 'Owner can archive a project'),
  blocked('Projects', 'Project ownership', 'Unauthorized project changes are rejected'),

  scenario(
    'Notifications',
    'Notification authorization boundary',
    'Unauthenticated users cannot list notifications',
    'rejects anonymous access to /api/notifications',
    'vitest',
  ),
  blocked('Notifications', 'Notification list', 'Notifications load'),
  blocked('Notifications', 'Like notification', 'Like activity creates a notification'),
  blocked('Notifications', 'Comment notification', 'Comment activity creates a notification'),
  blocked(
    'Notifications',
    'Follow or join notification',
    'Supported relationship activity creates a notification',
  ),
  blocked('Notifications', 'Mark read', 'Notification is marked read'),
  blocked('Notifications', 'Unread count', 'Unread count is accurate'),

  blocked('Resources', 'View resources', 'Resources list loads'),
  blocked('Resources', 'Search/filter resources', 'Resource filters return matching resources'),
  blocked('Resources', 'Resource details', 'Resource details load'),

  scenario(
    'Settings',
    'Settings authorization boundary',
    'Unauthenticated users cannot load settings',
    'rejects anonymous access to /api/settings',
    'vitest',
  ),
  blocked('Settings', 'Load settings', 'Settings load'),
  blocked('Settings', 'Update settings', 'Updated settings persist'),
  blocked('Settings', 'Account-related settings', 'Account settings follow security rules'),

  scenario(
    'Navigation',
    'Protected direct navigation',
    'Direct protected navigation settles at authentication',
    'direct protected navigation',
    'playwright',
  ),
  scenario(
    'Navigation',
    'Auth history navigation',
    'Back navigation returns to the prior auth page',
    'signup and login navigation',
    'playwright',
  ),
  scenario(
    'API / Security',
    'Security headers',
    'Responses include baseline security headers',
    'keeps the public API envelope',
    'vitest',
  ),
  scenario(
    'API / Security',
    'Unknown route envelope',
    'Unknown routes return a structured 404',
    'returns a structured 404',
    'vitest',
  ),
  scenario(
    'API / Security',
    'CSRF boundary',
    'Cookie-authenticated mutations require CSRF protection',
    'requires CSRF protection',
    'vitest',
  ),
  scenario(
    'API / Security',
    'CORS boundary',
    'Arbitrary origins cannot receive credentialed API access',
    'arbitrary origin',
    'vitest',
  ),
  scenario(
    'API / Security',
    'Sensitive response handling',
    'Submitted secrets are not echoed in responses',
    'does not emit submitted passwords',
    'vitest',
  ),

  blocked('Database', 'Persistence', 'Created data persists in the dedicated QA database'),
  blocked('Database', 'Data retrieval', 'Persisted data can be retrieved'),
  blocked('Database', 'Referential integrity', 'Related records resolve consistently'),
  blocked(
    'Database',
    'Duplicate and invalid data handling',
    'Invalid or duplicate data is rejected safely',
  ),
  scenario(
    'Performance',
    'Health endpoint latency',
    'Health endpoint responds successfully within the smoke baseline',
    'health-smoke',
    'performance',
  ),

  scenario(
    'Chat',
    'Create conversation',
    'A direct conversation is created or reused without duplicates',
    'two-user chat',
    'playwright',
  ),
  scenario(
    'Chat',
    'Send message',
    'The sender sees a persisted message',
    'two-user chat',
    'playwright',
  ),
  scenario(
    'Chat',
    'Realtime delivery',
    'The receiver gets the message through Socket.IO',
    'two-user chat',
    'playwright',
  ),
  scenario(
    'Chat',
    'Reply',
    'The original sender receives the reply through Socket.IO',
    'two-user chat',
    'playwright',
  ),
  scenario(
    'Chat',
    'Message persistence',
    'Messages remain after both clients refresh',
    'two-user chat',
    'playwright',
  ),
  manual(
    'Chat',
    'Socket reconnect diagnostics',
    'Manual verification of recovery after an interrupted network connection',
  ),
];
