import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, RefreshCcw, UserRound } from 'lucide-react';
import { Badge, Button, Card, EmptyState, ErrorState, SectionHeading } from '../../components/ui';
import { apiErrorMessage } from '../../lib/api-state';
import { getAdminSuspiciousActivity } from '../../features/admin/admin.api';

export function AdminModeration({ onNavigate }: { onNavigate: (target: string) => void }) {
  const signals = useQuery({ queryKey: ['admin-moderation'], queryFn: getAdminSuspiciousActivity });
  return <section className="space-y-6"><SectionHeading eyebrow="Safety" title="Suspicious activity" description="Investigation signals for human review. No automatic punishment is applied." action={<Button variant="secondary" onClick={() => void signals.refetch()}><RefreshCcw className="h-4 w-4" />Refresh</Button>} />{signals.isLoading ? <Card className="p-8 text-sm text-muted">Scanning current signals…</Card> : signals.error ? <ErrorState message={apiErrorMessage(signals.error, 'Moderation signals are unavailable.')} onRetry={() => void signals.refetch()} /> : !signals.data?.signals.length ? <EmptyState title="No suspicious signals" description="The current review signal set is clear." /> : <div className="grid gap-4 lg:grid-cols-2">{signals.data.signals.map((item) => <Card key={item.id} className="p-5"><div className="flex items-start gap-3"><span className="rounded-xl bg-amber-50 p-2.5 text-amber-700"><AlertTriangle className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge tone={item.risk === 'HIGH' ? 'danger' : 'warning'}>{item.risk}</Badge><span className="text-xs text-muted">{item.id}</span></div><h2 className="mt-3 font-bold text-ink">{item.signal}</h2>{item.user ? <p className="mt-1 flex items-center gap-1 text-sm text-muted"><UserRound className="h-4 w-4" />{item.user.displayName} · @{item.user.username}</p> : null}<div className="mt-3 flex flex-wrap gap-2">{item.user?._id ? <Button size="sm" variant="secondary" onClick={() => onNavigate(`/admin/users/${item.user?._id}`)}>Investigate user</Button> : null}{item.targetType === 'REPORT' ? <Button size="sm" variant="ghost" onClick={() => onNavigate('/admin/reports')}>Review reports</Button> : null}</div></div></div></Card>)}</div>}<p className="text-xs text-muted">Generated {signals.data ? new Date(signals.data.generatedAt).toLocaleString() : '—'}</p></section>;
}
