import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, CheckCheck, RefreshCcw } from 'lucide-react';
import { Badge, Button, Card, EmptyState, ErrorState, SectionHeading } from '../../components/ui';
import { apiErrorMessage } from '../../lib/api-state';
import { getAdminNotifications, markAdminNotificationRead, markAllAdminNotificationsRead } from '../../features/admin/admin.api';

export function AdminNotifications({ onNavigate }: { onNavigate: (target: string) => void }) {
  const client = useQueryClient();
  const notifications = useQuery({ queryKey: ['admin-notifications'], queryFn: () => getAdminNotifications({ limit: 50 }) });
  const read = useMutation({ mutationFn: markAdminNotificationRead, onSuccess: () => void client.invalidateQueries({ queryKey: ['admin-notifications'] }) });
  const readAll = useMutation({ mutationFn: markAllAdminNotificationsRead, onSuccess: () => void client.invalidateQueries({ queryKey: ['admin-notifications'] }) });
  return <section className="space-y-6"><SectionHeading eyebrow="System" title="Notifications" description="Grouped operational signals for reports, moderation, and platform health." action={<div className="flex gap-2"><Button variant="secondary" onClick={() => void notifications.refetch()}><RefreshCcw className="h-4 w-4" />Refresh</Button><Button onClick={() => readAll.mutate()} disabled={readAll.isPending || !notifications.data?.unreadCount}><CheckCheck className="h-4 w-4" />Read all</Button></div>} /><Card className="flex items-center gap-3 p-4"><Bell className="h-5 w-5 text-brand-700" /><p className="text-sm font-semibold text-ink">{notifications.data?.unreadCount ?? 0} unread notifications</p></Card>{notifications.isLoading ? <Card className="p-8 text-sm text-muted">Loading notifications…</Card> : notifications.error ? <ErrorState message={apiErrorMessage(notifications.error, 'Notifications are unavailable.')} onRetry={() => void notifications.refetch()} /> : !notifications.data?.items.length ? <EmptyState title="You are all caught up" description="New platform signals will appear here." /> : <div className="space-y-3">{notifications.data.items.map((item) => <Card key={item.id} className={`p-5 ${item.readAt ? '' : 'border-brand-300 bg-brand-50/30'}`}><div className="flex items-start gap-4"><span className="rounded-xl bg-brand-50 p-2.5 text-brand-700"><Bell className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-ink">{item.title}</h2><Badge tone={item.priority === 'HIGH' || item.priority === 'CRITICAL' ? 'warning' : 'neutral'}>{item.priority}</Badge></div><p className="mt-1 text-sm text-muted">{item.body ?? 'Open this notification for more context.'}</p><p className="mt-2 text-xs text-muted">{new Date(item.createdAt).toLocaleString()}</p><div className="mt-3 flex flex-wrap gap-2">{item.entityType === 'REPORT' ? <Button size="sm" variant="secondary" onClick={() => onNavigate(`/admin/reports/${item.entityId}`)}>Open report</Button> : item.entityType === 'MODERATION' ? <Button size="sm" variant="secondary" onClick={() => onNavigate('/admin/moderation')}>Open moderation</Button> : null}{!item.readAt ? <Button size="sm" variant="ghost" onClick={() => read.mutate(item.id)} disabled={read.isPending}>Mark read</Button> : null}</div></div></div></Card>)}</div>}</section>;
}
