import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Badge, Button, Card, EmptyState, ErrorState, SectionHeading } from '../../components/ui';
import { apiErrorMessage } from '../../lib/api-state';
import { getAdminClubs, reviewAdminClub } from '../../features/admin/admin.api';
import type { ClubStatus } from '@campusconnection/shared';

export function AdminClubs() {
  const client = useQueryClient(); const [status, setStatus] = useState<ClubStatus>('PENDING');
  const clubs = useQuery({ queryKey: ['admin-clubs', status], queryFn: () => getAdminClubs(status) });
  const review = useMutation({ mutationFn: ({ id, next }: { id: string; next: Exclude<ClubStatus, 'PENDING'> }) => reviewAdminClub(id, next, next === 'REJECTED' ? 'Club application did not meet verification requirements.' : undefined), onSuccess: () => void client.invalidateQueries({ queryKey: ['admin-clubs'] }) });
  const items = clubs.data?.data ?? [];
  return <section className="space-y-6"><SectionHeading eyebrow="Management" title="Clubs" description="Review applications and moderate verified campus organizations." action={<Button variant="secondary" onClick={() => void clubs.refetch()}>Refresh</Button>} /><div className="flex flex-wrap gap-2">{(['PENDING', 'APPROVED', 'SUSPENDED', 'REJECTED'] as ClubStatus[]).map((item) => <button key={item} type="button" onClick={() => setStatus(item)} className={`rounded-full px-4 py-2 text-xs font-bold ${item === status ? 'bg-brand-600 text-white' : 'bg-[var(--surface-secondary)] text-muted ring-1 ring-line'}`}>{item}</button>)}</div>{clubs.isLoading ? <Card className="p-8 text-sm text-muted">Loading club applications...</Card> : clubs.error ? <ErrorState message={apiErrorMessage(clubs.error, 'Club applications are unavailable.')} onRetry={() => void clubs.refetch()} /> : !items.length ? <EmptyState title={`No ${status.toLowerCase()} clubs`} description="There are no records in this review queue." /> : <div className="grid gap-4">{items.map((club) => <Card key={club.id} className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="type-display text-lg font-bold text-ink">{club.name}</h2><Badge tone={club.status === 'APPROVED' ? 'success' : club.status === 'REJECTED' ? 'danger' : 'warning'}>{club.status}</Badge></div><p className="mt-1 text-sm font-semibold text-brand-700">{club.category} · {club.privacy.toLowerCase()}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{club.description}</p><p className="mt-3 text-xs text-muted">Owner ID: {club.ownerId} · Submitted {new Date(club.createdAt).toLocaleDateString()}</p></div><div className="flex flex-wrap gap-2">{club.status === 'PENDING' ? <><Button size="sm" onClick={() => review.mutate({ id: club.id, next: 'APPROVED' })}>Approve</Button><Button size="sm" variant="danger" onClick={() => review.mutate({ id: club.id, next: 'REJECTED' })}>Reject</Button></> : club.status === 'APPROVED' ? <Button size="sm" variant="danger" onClick={() => review.mutate({ id: club.id, next: 'SUSPENDED' })}>Suspend</Button> : club.status === 'SUSPENDED' ? <Button size="sm" variant="success" onClick={() => review.mutate({ id: club.id, next: 'APPROVED' })}>Restore</Button> : null}</div></div></Card>)}</div>}{review.error ? <p className="text-sm font-semibold text-red-600">{apiErrorMessage(review.error, 'Club review failed.')}</p> : null}</section>;
}
