import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { RefreshCcw } from 'lucide-react';
import { Badge, Button, Card, EmptyState, ErrorState, SectionHeading } from '../../components/ui';
import { apiErrorMessage } from '../../lib/api-state';
import { getAdminAuditLogs } from '../../features/admin/admin.api';

export function AdminAuditLogs() {
  const [search, setSearch] = useState('');
  const [action, setAction] = useState('');
  const logs = useQuery({ queryKey: ['admin-audit', search, action], queryFn: () => getAdminAuditLogs({ ...(search ? { search } : {}), ...(action ? { action } : {}), limit: 50 }) });
  return <section className="space-y-6"><SectionHeading eyebrow="System" title="Audit logs" description="Append-only administrative and security actions for investigation and accountability." action={<Button variant="secondary" onClick={() => void logs.refetch()}><RefreshCcw className="h-4 w-4" />Refresh</Button>} /><Card className="p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto]" role="search"><input aria-label="Search audit logs" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search action, actor, or target…" className="rounded-xl border border-line bg-[var(--surface-secondary)] px-3 py-2.5 text-sm text-ink" /><input aria-label="Filter audit action" value={action} onChange={(event) => setAction(event.target.value)} placeholder="Action e.g. REPORT_CREATED" className="rounded-xl border border-line bg-[var(--surface-secondary)] px-3 py-2.5 text-sm text-ink" /></div></Card>{logs.isLoading ? <Card className="p-8 text-sm text-muted">Loading audit logs…</Card> : logs.error ? <ErrorState message={apiErrorMessage(logs.error, 'Audit logs are unavailable.')} onRetry={() => void logs.refetch()} /> : !logs.data?.items.length ? <EmptyState title="No audit records" description="Administrative activity will appear here." /> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left"><thead className="border-b border-line bg-[var(--surface-secondary)] text-xs uppercase tracking-wide text-muted"><tr><th className="px-5 py-4">Action</th><th className="px-4 py-4">Actor</th><th className="px-4 py-4">Target</th><th className="px-4 py-4">Reason</th><th className="px-4 py-4">Time</th></tr></thead><tbody className="divide-y divide-[var(--border-subtle)]">{logs.data.items.map((item) => <tr key={item.id}><td className="px-5 py-4"><Badge tone="neutral">{item.action}</Badge></td><td className="px-4 py-4 text-sm text-muted">{item.actor ? `@${item.actor.username}` : 'System'}</td><td className="px-4 py-4 text-sm text-muted">{item.targetType ? `${item.targetType} · ${item.targetId ?? ''}` : '—'}</td><td className="max-w-md truncate px-4 py-4 text-sm text-muted">{item.reason ?? '—'}</td><td className="px-4 py-4 text-xs text-muted">{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></Card>}</section>;
}
